In [1]:
import pandas as pd 
import numpy as np
pd.set_option('max_colwidth', 400)

# Extract the Airlines_Delay_Cause.csv Data

In [2]:
# Read the data into a pandas DataFrame
airlines_delay_cause_df = pd.read_csv('Airline_Delay_Cause.csv')
airlines_delay_cause_df.head()

,year,month,carrier,carrier_name,airport,airport_name,arr_flights,arr_del15,carrier_ct,weather_ct,...,security_ct,late_aircraft_ct,arr_cancelled,arr_diverted,arr_delay,carrier_delay,weather_delay,nas_delay,security_delay,late_aircraft_delay
0,2023,4,9E,Endeavor Air Inc.,ABY,"Albany, GA: Southwest Georgia Regional",85.0,7.0,3.00,0.00,...,0.0,0.92,0.0,2.0,428.0,250.0,0.0,87.0,0.0,91.0
1,2023,4,9E,Endeavor Air Inc.,AEX,"Alexandria, LA: Alexandria International",46.0,5.0,3.63,0.61,...,0.0,0.00,0.0,1.0,272.0,153.0,67.0,52.0,0.0,0.0
2,2023,4,9E,Endeavor Air Inc.,AGS,"Augusta, GA: Augusta Regional at Bush Field",61.0,5.0,0.68,0.07,...,0.0,0.93,0.0,1.0,204.0,36.0,2.0,141.0,0.0,25.0
3,2023,4,9E,Endeavor Air Inc.,ALB,"Albany, NY: Albany International",211.0,29.0,9.86,1.00,...,0.0,13.93,1.0,0.0,1346.0,384.0,39.0,115.0,0.0,808.0
4,2023,4,9E,Endeavor Air Inc.,ATL,"Atlanta, GA: Hartsfield-Jackson Atlanta International",1390.0,140.0,41.20,5.11,...,0.0,64.59,0.0,2.0,12486.0,4655.0,403.0,1190.0,0.0,6238.0

In [3]:
# Get a brief summary of the airline_delay_cause DataFrame
airlines_delay_cause_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19708 entries, 0 to 19707
Data columns (total 21 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   year                 19708 non-null  int64
 1   month                19708 non-null  int64
 2   carrier              19708 non-null  object
 3   carrier_name         19708 non-null  object
 4   airport              19708 non-null  object
 5   airport_name         19708 non-null  object
 6   arr_flights          19699 non-null  float64
 7   arr_del15            19697 non-null  float64
 8   carrier_ct           19699 non-null  float64
 9   weather_ct           19699 non-null  float64
 10  nas_ct               19699 non-null  float64
 11  security_ct          19699 non-null  float64
 12  late_aircraft_ct     19699 non-null  float64
 13  arr_cancelled        19699 non-null  float64
 14  arr_diverted         19699 non-null  float64
 15  arr_delay            19699 non-null  float64
 16  carrier_delay        19699 non-null  float64
 17  weather_delay        19699 non-null  float64
 18  nas_delay            19699 non-null  float64
 19  security_delay       19699 non-null  float64
 20  late_aircraft_delay  19699 non-null  float64
dtypes: float64(15), int64(2), object(4)
memory usage: 3.2+ MB

In [4]:
# Get the airline_delay_cause_df columns
airlines_delay_cause_df.columns

Index(['year', 'month', 'carrier', 'carrier_name', 'airport', 'airport_name',
       'arr_flights', 'arr_del15', 'carrier_ct', 'weather_ct', 'nas_ct',
       'security_ct', 'late_aircraft_ct', 'arr_cancelled', 'arr_diverted',
       'arr_delay', 'carrier_delay', 'weather_delay', 'nas_delay',
       'security_delay', 'late_aircraft_delay'],
      dtype='object')

In [5]:
# get the unique carrie name and airport name 
carrier_name = airlines_delay_cause_df['carrier_name'].unique()
airports = airlines_delay_cause_df['airport_name'].unique()
carrier_name

array(['Endeavor Air Inc.', 'American Airlines Inc.',
       'Alaska Airlines Inc.', 'JetBlue Airways', 'Delta Air Lines Inc.',
       'Frontier Airlines Inc.', 'Allegiant Air',
       'Hawaiian Airlines Inc.', 'Envoy Air', 'Spirit Air Lines',
       'PSA Airlines Inc.', 'SkyWest Airlines Inc.',
       'United Air Lines Inc.', 'Southwest Airlines Co.',
       'Republic Airline', 'Horizon Air', 'Mesa Airlines Inc.'],
      dtype=object)

In [6]:
# get the lenght of carrier_name 
print(len(carrier_name))

17

In [7]:
# GET THE LENGHT OF AIRPOTS
print (len(airports))

390

In [8]:
#Rename the columns
airlines_delay_cause_df= airlines_delay_cause_df.rename(columns={'arr_flights': 'total_arriving_flights',\
                                                                 'airport': 'Airport Code',\
                                                                 'carrier_ct':'air_carrier_delay',\
                                                                 'weather_ct': 'wheather_delay', \
                                                                 'nas_ct':'nat_aviation_delay',\
                                                                 'carrier_delay':'carrier_ttl_delay',\
                                                                 'arr_cancelled': 'Cancelled_flights',\
                                                                 'weather_delay': 'weather_ttl_delay',\
                                                                 'nas_delay':'National_aviation_ttl_delay',\
                                                                 'security_delay':'security_ttl_delay',
                                                                 'late_aircraft_delay':"late_aircraft_ttl_delay"
                                                                })

airlines_delay_cause_df.head()

,year,month,carrier,carrier_name,Airport Code,airport_name,total_arriving_flights,arr_del15,air_carrier_delay,wheather_delay,...,security_ct,late_aircraft_ct,Cancelled_flights,arr_diverted,arr_delay,carrier_ttl_delay,weather_ttl_delay,National_aviation_ttl_delay,security_ttl_delay,late_aircraft_ttl_delay
0,2023,4,9E,Endeavor Air Inc.,ABY,"Albany, GA: Southwest Georgia Regional",85.0,7.0,3.00,0.00,...,0.0,0.92,0.0,2.0,428.0,250.0,0.0,87.0,0.0,91.0
1,2023,4,9E,Endeavor Air Inc.,AEX,"Alexandria, LA: Alexandria International",46.0,5.0,3.63,0.61,...,0.0,0.00,0.0,1.0,272.0,153.0,67.0,52.0,0.0,0.0
2,2023,4,9E,Endeavor Air Inc.,AGS,"Augusta, GA: Augusta Regional at Bush Field",61.0,5.0,0.68,0.07,...,0.0,0.93,0.0,1.0,204.0,36.0,2.0,141.0,0.0,25.0
3,2023,4,9E,Endeavor Air Inc.,ALB,"Albany, NY: Albany International",211.0,29.0,9.86,1.00,...,0.0,13.93,1.0,0.0,1346.0,384.0,39.0,115.0,0.0,808.0
4,2023,4,9E,Endeavor Air Inc.,ATL,"Atlanta, GA: Hartsfield-Jackson Atlanta International",1390.0,140.0,41.20,5.11,...,0.0,64.59,0.0,2.0,12486.0,4655.0,403.0,1190.0,0.0,6238.0

In [9]:
#grouping by carrier_name 
total_flights_arrived_df = airlines_delay_cause_df.groupby(['carrier_name'])[['total_arriving_flights', 'air_carrier_delay', 'wheather_delay', 'nat_aviation_delay']].sum()
total_flights_arrived_df

,total_arriving_flights,air_carrier_delay,wheather_delay,nat_aviation_delay
carrier_name,,,,
Alaska Airlines Inc.,234994.0,12897.35,1275.28,18597.97
Allegiant Air,115868.0,8654.31,1916.74,10402.52
American Airlines Inc.,903469.0,67375.90,8356.58,54640.26
Delta Air Lines Inc.,920359.0,64330.66,4904.12,41477.77
Endeavor Air Inc.,213886.0,9646.75,1349.01,12468.81
Envoy Air,234358.0,10546.33,3400.27,14282.90
Frontier Airlines Inc.,161250.0,16054.52,808.05,15194.72
Hawaiian Airlines Inc.,77161.0,11107.75,483.21,1322.24
Horizon Air,58041.0,3034.36,362.97,2484.33
JetBlue Airways,279570.0,33760.14,1502.61,23146.55
Mesa Airlines Inc.,73313.0,5467.76,1029.55,3132.60
PSA Airlines Inc.,198307.0,8863.11,1930.73,10162.39
Republic Airline,307772.0,12828.11,1813.35,22175.04
SkyWest Airlines Inc.,705400.0,74065.00,13365.00,4089.00
Southwest Airlines Co.,1359925.0,108372.51,3733.27,53949.96
Spirit Air Lines,247660.0,18144.23,1929.87,27215.06
United Air Lines Inc.,666171.0,44627.06,3632.10,41614.68

In [11]:
#drop off some carrier_names and leave only the top 11 airlines in the USA 
cleaned_top_flights_df = total_flights_arrived_df.drop(['Allegiant Air','Endeavor Air Inc.','Horizon Air','Mesa Airlines Inc.','PSA Airlines Inc.','Republic Airline'])
cleaned_top_flights_df

,total_arriving_flights,air_carrier_delay,wheather_delay,nat_aviation_delay
carrier_name,,,,
Alaska Airlines Inc.,234994.0,12897.35,1275.28,18597.97
American Airlines Inc.,903469.0,67375.90,8356.58,54640.26
Delta Air Lines Inc.,920359.0,64330.66,4904.12,41477.77
Envoy Air,234358.0,10546.33,3400.27,14282.90
Frontier Airlines Inc.,161250.0,16054.52,808.05,15194.72
Hawaiian Airlines Inc.,77161.0,11107.75,483.21,1322.24
JetBlue Airways,279570.0,33760.14,1502.61,23146.55
SkyWest Airlines Inc.,705400.0,74065.00,13365.00,4089.00
Southwest Airlines Co.,1359925.0,108372.51,3733.27,53949.96
Spirit Air Lines,247660.0,18144.23,1929.87,27215.06
United Air Lines Inc.,666171.0,44627.06,3632.10,41614.68

In [13]:
#Exporting the dataframe as a csv file 
cleaned_top_flights_df.to_csv("cleaned_top_flights.csv")